spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://anindochoudhury2004_db_user:CZgMY2y24FZUxZFe@cluster0.dwiubed.mongodb.net/journal_db?appName=Cluster0

server:
  port: 8080
  servlet:
    context-path: /journal
